[metadata]
name = "all"
description = "A channel to select files and directories"
requirements = ["fd"]

[source]
command = ["fd -d 1", "fd", "fd --hidden"]

[preview]
command = "bat -n --color=always '{}' 2>/dev/null || eza -la --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
ctrl-e = "actions:edit"

[actions.edit]
description = "Open in editor"
command = "${EDITOR:-nvim} '{}'"
shell = "bash"
mode = "execute"
