---
name: Test Setup dotfiles on Mac OS

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["master", "main"]
    paths:
      - ".github/workflows/main.yml"
      - "setup.sh"
      - "_*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # Ensure all files are checked out

      - name: Move repo to HOME directory
        run: |
          cp -r . "$HOME/"
          cd $HOME

      - name: Run setup dotfiles
        working-directory: /Users/runner
        run: |
          set -eo pipefail
          export CI=1
          ./setup.sh # Test dotfile setup
